# Generated by Django 2.2.4 on 2020-12-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_and_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
